### PR TITLE
Closes #139

### LINKED ISSUE #139: Abstract Test 37 seemingly incorrect
**Describe the bug**
Table C.9 lists position as not required in data_queries. As such, one would expect it to be skipped if not present in a collection but it fails if not found

**To Reproduce**
Run the test against a collection which does not list position in data_queries

**Expected behavior**
The test should be skipped, not failed

**Screenshots**

**Additional context**
The failure text is:
<message>
<![CDATA[ Fails Abstract Test 37. Therefore could not verify the implementation passes Abstract Tests 39, 41, 43, 45, 47, and 49. Expected information that matches the selection criteria is returned for Position query. The position element is missing from the data_queries element of the collection airmet . The position element is missing from the data_queries element of the collection metar . The position element is missing from the data_queries element of the collection vaa . ]]>
</message>.

### PR DESCRIPTION
**Pull request by bpross-52n**
Closes #139

### CODE REVIEW

File: src/main/java/org/opengis/cite/ogcapiedr10/queries/PositionQueryProcessor.java [hunk 1]
```diff
@@ -27,7 +34,7 @@ public String validatePositionQueryUsingParameters(Set<String> collectionIds, St
             String url = JsonUtils.getCollectionURL(rootUri, collectionId);
 
             Response response = JsonUtils.getCollectionResponse(rootUri, collectionId, ini);
-            JsonPath jsonResponse = response.jsonPath();
+            JsonPath jsonResponse = JsonPath.from(new java.io.File("D:\\52n\\Projekte\\CITE Consulting\\edr-issue-133-collection-response.json"));
```
Comment (julianzz98) [inline src/main/java/org/opengis/cite/ogcapiedr10/queries/PositionQueryProcessor.java:37]: It seems you used a local file path for debugging. Could you remove it and revert to the original logic?

**Review by julianzz98 — CHANGES_REQUESTED** [review]

File: src/main/java/org/opengis/cite/ogcapiedr10/queries/PositionQueryProcessor.java (hunk 1 above)
Comment (bpross-52n) [reply src/main/java/org/opengis/cite/ogcapiedr10/queries/PositionQueryProcessor.java]: Good work spotting this. I reverted the changes. Thanks!

**Review by julianzz98 — APPROVED** [review]
Code looks good now and can be merged @dstenger!
