### PR TITLE
Closes #112

### LINKED ISSUE #112: OGC API - EDR ETS: Testing for "coords" within Cube Query, Should be bbox
In testing the EDR ETS, There is a failed test for the "coords" query parameter for the Cube query. According to the specification, there is no "coords" query parameter, but rather a "bbox" query parameter. See screenshot for failed test. See this issue for additional context:

https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/423

ets_cube_fail

### PR DESCRIPTION
**Pull request by bpross-52n**
Closes #112

### CODE REVIEW

File: src/main/java/org/opengis/cite/ogcapiedr10/collections/CubeCollections.java [hunk 1]
```diff
@@ -48,17 +48,17 @@ public class CubeCollections extends AbstractFeatures {
 	CollectionsTime ct= new CollectionsTime();
 	/**
 	 * <pre>
-	 * Abstract Test 70: Validate that the coords query parameters are constructed correctly. (cube)
+	 * Abstract Test 70: Validate that the bbox query parameters are constructed correctly. (cube)
```
Comment (dstenger) [inline src/main/java/org/opengis/cite/ogcapiedr10/collections/CubeCollections.java:51]: The standard (https://docs.ogc.org/is/19-086r4/19-086r4.html) still uses the old (wrong) sentence. I prefer it to leave it like that and to add a short comment explaining that the abstract test of the specification is wrong so that the test is implemented differently.

**Review by dstenger — CHANGES_REQUESTED** [review]

**Comment by dstenger** [comment]
Also, do you have a test service to verify the fix?

**Comment by bpross-52n** [comment]
> Also, do you have a test service to verify the fix?

@dstenger You can test the fix with https://labs.metoffice.gov.uk/edr (and https://labs.metoffice.gov.uk/edr/api for API definition)

**Review by dstenger — APPROVED** [review]
